[default]
log_level = "info"
uptimer_log_level = "info"

reader_plugin = "readers.probes.http"
writer_plugin = "writers.stdout"

probe_urls = """
    https://github.com,
    https://janw.xyz
"""
probe_interval = -1

kafka_ssl_check_hostname = false
kafka_security_protocol = "SSL"

[development]

database_url = "postgres://postgres:postgres@localhost/uptimer"

[testing]
log_level = "warning"
uptimer_log_level = "debug"

# Basic settings
reader_plugin = "some.plugin"

# For uptimer.plugins.readers.kafka
# and uptimer.plugins.writers.kafka
kafka_bootstrap_server = "localhost:9092"

# For uptimer.plugins.readers.kafka
kafka_reader_topic = "sometopic"

# For uptimer.plugins.writers.kafka
kafka_writer_topic = "sometopic"

# For uptimer.plugins.writers.postgres
database_url = "postgres://testuser:testpassword@localhost/test_db"
