apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: uptimer-producer
spec:
  replicas: 2
  serviceName: uptimer-producer
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: uptimer-producer
  template:
    metadata:
      labels:
        app: uptimer-producer
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: uptimer
          image: willhaus/uptimer
          volumeMounts:
            - name: kafka-auth
              readOnly: true
              mountPath: /credentials
          envFrom:
            - secretRef:
                name: kafka-connection
          env:
            - name: READER_PLUGIN
              value: readers.probes.http
            - name: WRITER_PLUGIN
              value: writers.kafka

            - name: KAFKA_SSL_CAFILE
              value: /credentials/ca.pem
            - name: KAFKA_SSL_KEYFILE
              value: /credentials/service.key
            - name: KAFKA_SSL_CERTFILE
              value: /credentials/service.cert

            - name: PROBE_INTERVAL
              value: "30"
            - name: PROBE_URLS
              value: |
                - https://github.com
                - https://janw.xyz

            - name: DISTRIBUTED_WORKERS_ENABLED
              value: "true"
            - name: DISTRIBUTED_WORKERS_TOTAL
              value: "2"
            - name: DISTRIBUTED_WORKERS_INDEX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      volumes:
        - name: kafka-auth
          secret:
            secretName: kafka-auth
