name: Linters

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up python environment
        uses: actions/setup-python@v2
        with:
            python-version: "3.8"

      - name: Run pre-commit
        uses: pre-commit/action@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  conventional-commits:
    runs-on: ubuntu-latest
    container: commitizen/commitizen:2
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Check for conventional commit formatting
        run: |
          cz check --rev-range 0.1.0..HEAD
